### ISSUE TITLE
工单任务可以执行脚本和支持传参数吗

### ISSUE THREAD

**Issue by opcache** [Duke1616/ecmdb#5]
工单任务可以执行脚本和支持传参数吗
场景：比如我想申请工单域名解析到一个IP，脚本是可以解析IP的，但要工单里面传给脚本
脚本格式 xxx.sh 1.2.3.4 xxx.aaa.com
同问工单如何传参给下游，工单审批过后让自动根据工单所填的参数自动执行任务。
如购买服务器工单，审批完成后，自动根据配置参数执行脚本或是调远程其它服务的API也行。

**Comment by Duke1616** [comment]
在我设计的工单系统中是满足你的需求的，具体的方式如下。

自动化任务可以在平台中编写python、shell，支持传递参数（也就是工单模版中定义的信息）、以及工作节点环境变量（主要用于user、pwd这类信息，直接定义在脚本中不合适）。
具体实现需要先自己创建一个工单模版、绑定一个流程，在流程里面绘制自动化节点，绑定你所要执行的工作节点 和 执行的任务脚本，当有工单任务触发流转到自动化节点时会发送到消息到队列中，ework-runner 接收到消息会自动执行你的任务。

增强能力：比如你的任务执行失败，你可以手动篡改参数、变量进行重试任务。

**Comment by opcache** [comment]
> 在我设计的工单系统中是满足你的需求的，具体的方式如下。
> 
> 自动化任务可以在平台中编写python、shell，支持传递参数（也就是工单模版中定义的信息）、以及工作节点环境变量（主要用于user、pwd这类信息，直接定义在脚本中不合适）。 具体实现需要先自己创建一个工单模版、绑定一个流程，在流程里面绘制自动化节点，绑定你所要执行的工作节点 和 执行的任务脚本，当有工单任务触发流转到自动化节点时会发送到消息到队列中，ework-runner 接收到消息会自动执行你的任务。
> 
> 增强能力：比如你的任务执行失败，你可以手动篡改参数、变量进行重试任务。
好的，我找时间测试验证下，感谢开发这个项目，并开源出来，加油！
